using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    public static GameManager Instance {  get; private set; }

    [Header("States")]
    [SerializeField] private State state;
    [SerializeField] private State previousState;

    public enum State { StartingGame, PlayerTurn, EnemyTurn, FreeMovement, Lose }

    public State GameState => state;

    public static event EventHandler<OnStateEventArgs> OnStateChanged;

    public class OnStateEventArgs : EventArgs
    {
        public State newState;
    }

    private void OnEnable()
    {

    }

    private void OnDisable()
    {

    }

    private void Awake()
    {
        SetSingleton();
    }

    private void Start()
    {
        ChangeState(State.StartingGame);
    }

    private void SetSingleton()
    {
        if(Instance == null)
        {
            Instance = this;
        }
        else
        {
            Debug.LogWarning("There is more than one GameManager instance, proceding to destroy duplicate");
            Destroy(gameObject);
        }
    }

    private void SetGameState(State state)
    {
        SetPreviousState(this.state);
        this.state = state;
    }

    private void SetPreviousState(State state)
    {
        previousState = state;
    }

    private void ChangeState(State state)
    {
        SetGameState(state);
        OnStateChanged?.Invoke(this, new OnStateEventArgs { newState = state });
    }
}
